// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuWG6cY9PZmDFhzdHFtNKsqNAX9Y4csE',
    appId: '1:469435981910:web:53dcbc0405cd7f02e45bf7',
    messagingSenderId: '469435981910',
    projectId: 'project-f1f05',
    authDomain: 'project-f1f05.firebaseapp.com',
    databaseURL: 'https://project-f1f05-default-rtdb.firebaseio.com',
    storageBucket: 'project-f1f05.appspot.com',
    measurementId: 'G-RFSPX08FNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0tLF0PBfOlHZZKGBF6yHNrAcia2AVo_M',
    appId: '1:469435981910:android:b1f2704d5492a088e45bf7',
    messagingSenderId: '469435981910',
    projectId: 'project-f1f05',
    databaseURL: 'https://project-f1f05-default-rtdb.firebaseio.com',
    storageBucket: 'project-f1f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKO_6Zuz0KBpqYfG3tufUFOjjotenn4M',
    appId: '1:469435981910:ios:7f1ab21bc6081225e45bf7',
    messagingSenderId: '469435981910',
    projectId: 'project-f1f05',
    databaseURL: 'https://project-f1f05-default-rtdb.firebaseio.com',
    storageBucket: 'project-f1f05.appspot.com',
    iosClientId: '469435981910-3alshdqdc0aka7r3pkt3lshhu1jppe05.apps.googleusercontent.com',
    iosBundleId: 'com.example.clgProject',
  );
}
